### ISSUE TITLE
build failed without --harmony flag

### ISSUE THREAD

**Issue by rogerz** [imyelo/gulp-duojs#1]
For gulp task

```
gulp.task('main.js', function() {
  return gulp.src('src/js/index.js')
    .pipe($.duojs())
    .pipe(gulp.dest('app/scripts'));
});
```

Got the following error

```
/Users/zhangyujun/Workspace/we-sign-app/node_modules/gulp-duojs/node_modules/duo/node_modules/duo-css-compat/index.js:216
    }, component_compat, this);
       ^
ReferenceError: component_compat is not defined
    at Step.component_compat (/Users/zhangyujun/Workspace/we-sign-app/node_modules/gulp-duojs/node_modules/duo/node_modules/duo-css-compat/index.js:216:8)
    at Step.<anonymous> (/Users/zhangyujun/Workspace/we-sign-app/node_modules/gulp-duojs/node_modules/duo/node_modules/co/index.js:40:16)
    at call (/Users/zhangyujun/Workspace/we-sign-app/node_modules/gulp-duojs/node_modules/duo/node_modules/step.js/index.js:87:14)
    at null._onTimeout (/Users/zhangyujun/Workspace/we-sign-app/node_modules/gulp-duojs/node_modules/duo/node_modules/step.js/index.js:68:5)
    at Timer.listOnTimeout (timers.js:110:15)
```

It seems to be related to https://github.com/duojs/duo/issues/433

**Comment by imyelo** [comment]
+1. 
duo@0.11 may fixed this issue https://github.com/duojs/duo/pull/455

**Comment by rogerz** [comment]
Still failing but with a different error

```
 ✗ gulp duo
[20:51:05] Using gulpfile ~/Workspace/we-sign-app/gulpfile.js
[20:51:05] Starting 'main.js'...
[20:51:05] 'main.js' errored after 22 ms
[20:51:05] /Users/zhangyujun/Workspace/we-sign-app/node_modules/gulp-duojs/node_modules/duo/lib/duo.js:370
Duo.prototype.cleanCache = function *() {
                                    ^
SyntaxError: Unexpected token *
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/zhangyujun/Workspace/we-sign-app/node_modules/gulp-duojs/index.js:2:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

`gulp --harmony duo` is OK.

**Comment by rogerz** [comment]
unit test fails also.

```
npm test

> gulp-duojs@0.4.0 test /Users/zhangyujun/Workspace/gulp-duojs
> mocha

/Users/zhangyujun/Workspace/gulp-duojs/node_modules/duo/lib/duo.js:370
Duo.prototype.cleanCache = function *() {
                                    ^
SyntaxError: Unexpected token *
    at exports.runInThisContext (vm.js:73:16)
```

**Comment by rogerz** [comment]
test fails with iojs

```
npm test

> gulp-duojs@0.4.0 test /Users/zhangyujun/Workspace/gulp-duojs
> mocha



  gulp-cat
    1) should work in buffer mode


  0 passing (29ms)
  1 failing

  1) gulp-cat should work in buffer mode:
     Uncaught AssertionError: '' == <Buffer 28 66 75 6e 63 74 69 6f 6e 20 6f 75 74 65 72 28 6d 6f 64 75 6c 65 73 2c 20 63 61 63 68 65 2c 20 65 6e 74 72 69 65 73 29
      at DestroyableTransform.<anonymous> (test/index.js:27:20)
      at index.js:53:7
      at Duo.<anonymous> (index.js:35:7)



npm ERR! Test failed.  See above for more details.
```

**Comment by imyelo** [comment]
https://github.com/duojs/duo/blob/edfe92feec2e90f5289d963eb80b9a40c418b109/docs/cli.md#using-with-node-010
https://github.com/duojs/duo/issues/466

yes, we need to use the `--harmony-generators` flag after duo@0.11 :smile:
